FROM apache/superset:latest

# Chuyển sang root để có toàn quyền ghi vào thư mục môi trường ảo /app/.venv
USER root

# Sử dụng chính xác trình thực thi python của venv để cài gói
RUN /app/.venv/bin/python -m pip install --no-cache-dir psycopg2-binary pyathena

# Trả lại quyền chạy an toàn cho user superset mặc định
USER superset