FROM apache/superset:latest

# Chuyển sang user superset để cài thư viện vào đúng môi trường chạy của nó
USER superset

# Sử dụng pip mặc định của container để cài gói
RUN pip install --no-cache-dir psycopg2-binary pyathena
