name: 'ecommerce'
version: '1.0.0'
config-version: 2

profile: 'ecommerce'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  ecommerce:
    staging:          # Models in staging/
      +materialized: view     # Views for staging (logical layer)
    marts:            # Models in marts/
      +schema: marts
      +materialized: table    # Tables for curated marts
      +enabled: true
