version: 2

models:
  - name: mart_revenue_daily
    description: "Bảng tổng hợp doanh thu theo ngày, dùng trực tiếp cho Superset Dashboard."
    columns:
      - name: date_day
        description: "Ngày giao dịch chính xác (Temporal axis)"
        tests:
          - not_null
      - name: total_revenue
        description: "Tổng doanh thu bao gồm giá sản phẩm và phí vận chuyển"
        tests:
          - not_null

  - name: fact_order_items
    description: "Bảng sự kiện chi tiết của từng đơn hàng."
    columns:
      - name: order_id
        tests:
          - not_null
          # - unique  # Lưu ý: 1 order có thể có nhiều item, nên hãy kiểm tra kỹ logic trước khi set unique ở đây

  - name: dim_customers
    description: "Thông tin chi tiết về khách hàng, bao gồm vị trí địa lý và hành vi mua hàng cơ bản."
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
      - name: customer_city
        description: "Thành phố của khách hàng"
      - name: customer_state
        description: "Bang của khách hàng"

  - name: dim_products
    description: "Danh mục sản phẩm với thông tin về loại hàng và kích thước."
    columns:
      - name: product_id
        tests:
          - not_null
          - unique
      - name: product_category
        description: "Tên ngành hàng (đã được dịch sang tiếng Anh)"

  - name: dim_sellers
    description: "Thông tin về các nhà bán hàng (Sellers) trên hệ thống."
    columns:
      - name: seller_id
        tests:
          - not_null
          - unique
      - name: seller_city
        description: "Thành phố đặt kho của nhà bán hàng"

  - name: fact_payments
    description: "Bảng ghi nhận các giao dịch thanh toán cho từng đơn hàng."
    columns:
      - name: order_id
        tests:
          - not_null
      - name: payment_types
        description: "Phương thức thanh toán (có thể chứa nhiều loại, ví dụ: credit_card,voucher)"


  - name: dim_date
    description: "Bảng kích thước thời gian để hỗ trợ phân tích theo từng cấp độ ngày, tháng, quý, năm."
    columns:
      - name: date_id
        tests:
          - not_null
          - unique
      - name: year
        description: "Năm (YYYY)"
      - name: month
        description: "Tháng (1-12)"

  - name: dim_geolocation
    description: "Thông tin vị trí địa lý dựa trên mã ZIP code của Brazil."
    columns:
      - name: zip_code_prefix
        tests:
          - not_null
      - name: city
        description: "Tên thành phố tương ứng với mã ZIP"


