name: dbt_pipeline_ci_cd

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  run-dbt-tests:
    runs-on: ubuntu-latest
    
    # Kỹ thuật Senior: Chạy một Database "tạm thời" ngay trên GitHub
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: de_user
          POSTGRES_PASSWORD: de_password
          POSTGRES_DB: ecommerce_db
        ports:
          - 5432:5432
        # Đảm bảo Postgres đã sẵn sàng trước khi chạy dbt
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DBT_PROFILES_DIR: ./dbt_project
      POSTGRES_HOST: localhost # GitHub runner kết nối tới service qua localhost
      POSTGRES_USER: de_user
      POSTGRES_PASSWORD: de_password
      POSTGRES_DB: ecommerce_db
      POSTGRES_PORT: 5432
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        working-directory: ./dbt_project
        run: |
          pip install dbt-postgres==1.10.0
          dbt deps --project-dir ./ecommerce
          
      - name: dbt Debug (Kiểm tra kết nối)
        working-directory: ./dbt_project
        run: dbt debug --project-dir ./ecommerce --profiles-dir .
        
      # LƯU Ý: Trong môi trường CI thực tế, ta thường dùng Seed dữ liệu mẫu để test.
      # Hiện tại ta chỉ kiểm tra xem dbt có Compile và Debug được không.
      - name: dbt Compile
        working-directory: ./dbt_project
        run: dbt compile --project-dir ./ecommerce --profiles-dir .
